# Generated by Django 5.1.2 on 2025-02-01 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_event_event_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('task_deadline', models.DateField()),
                ('task_assigned_to', models.CharField(max_length=200)),
                ('task_status', models.CharField(default='Pending', max_length=200)),
                ('task_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
